name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Validate composer.json and composer.lock
          run: composer validate --strict

        - name: Cache Composer packages
          id: composer-cache
          uses: actions/cache@v2
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ steps.key-date.outputs.date }}-${{ hashFiles('composer.json') }}-${{ matrix.prefer-lowest }}

        - name: Composer install
          run: |
            if ${{ matrix.prefer-lowest == 'prefer-lowest' }}; then
              composer update --prefer-lowest --prefer-stable
            else
              composer update
            fi

        - name: Run PHPUnit
          run: |
            if [[ ${{ matrix.php-version }} == '8.0' ]]; then
              export CODECOVERAGE=1 && vendor/bin/phpunit --verbose --coverage-clover=coverage.xml
            else
              vendor/bin/phpunit
            fi
