name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '8.0']

    steps:
        - uses: actions/checkout@v2

        - name: Validate composer.json and composer.lock
          run: composer validate --strict

        - name: Cache Composer packages
          id: composer-cache
          uses: actions/cache@v2
          with:
            path: vendor
            key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-php-

        - name: Composer install
          run: |
            if ${{ matrix.prefer-lowest == 'prefer-lowest' }}; then
              composer update --prefer-lowest --prefer-stable
            else
              composer update
            fi

        - name: Run PHPUnit
          run: |
            if [[ ${{ matrix.php-version }} == '8.0' ]]; then
              export CODECOVERAGE=1 && vendor/bin/phpunit --verbose --coverage-clover=coverage.xml
            else
              vendor/bin/phpunit
            fi
